ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;  

DROP TABLE ADMIN.DANGKY;
DROP TABLE ADMIN.KHMO;
DROP TABLE ADMIN.SINHVIEN;
DROP TABLE ADMIN.PHANCONG;
DROP TABLE ADMIN.HOCPHAN;
DROP TABLE ADMIN.DONVI;
DROP TABLE ADMIN.NHANSU;
CREATE TABLE ADMIN.NHANSU (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI VARCHAR2(10),
    NGSINH DATE,
    PHUCAP NUMBER(10, 2),
    DT CHAR(10),
    VAITRO VARCHAR2(50),
    MADV VARCHAR2(20)
);

CREATE TABLE ADMIN.SINHVIEN (
    MASV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI VARCHAR2(10),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT CHAR(10),
    MACT VARCHAR2(20),
    MANGANH VARCHAR2(20),
    SOTCTL NUMBER(3),
    DTBTL NUMBER(4, 2)
);

CREATE TABLE DATTRONG.DONVI (
    MADV VARCHAR2(20) PRIMARY KEY,
    TENDV VARCHAR2(50),
    TRGDV VARCHAR2(20),
    FOREIGN KEY (TRGDV) REFERENCES ADMIN.NHANSU(MANV)
);

CREATE TABLE ADMIN.HOCPHAN (
    MAHP VARCHAR2(20) PRIMARY KEY,
    TENHP VARCHAR2(50),
    SOTC NUMBER(2),
    STLT NUMBER(2),
    STTH NUMBER(2),
    SOSVTD NUMBER(3),
    MADV VARCHAR2(20),
    FOREIGN KEY (MADV) REFERENCES ADMIN.DONVI(MADV)
);

CREATE TABLE ADMIN.KHMO (
    MAHP VARCHAR2(20),
    HK VARCHAR2(10),
    NAM VARCHAR2(4),
    MACT VARCHAR2(20),
    PRIMARY KEY (MAHP, HK, NAM, MACT),
    FOREIGN KEY (MAHP) REFERENCES ADMIN.HOCPHAN(MAHP)
);

CREATE TABLE ADMIN.PHANCONG (
    MAGV VARCHAR2(20),
    MAHP VARCHAR2(20),
    HK VARCHAR2(10),
    NAM VARCHAR2(4),
    MACT VARCHAR2(20),
    PRIMARY KEY (MAGV,MAHP, HK, NAM, MACT),
    FOREIGN KEY (MAHP) REFERENCES ADMIN.HOCPHAN(MAHP),
    FOREIGN KEY(MAGV) REFERENCES ADMIN.NHANSU(MANV)
)

CREATE TABLE ADMIN.DANGKY (
    MASV VARCHAR(20),
    MAGV VARCHAR2(20),
    MAHP VARCHAR2(20),
    HK VARCHAR2(10),
    NAM VARCHAR2(4),
    MACT VARCHAR2(20),
    DIEMTHI NUMBER(4,2),
    DIEMQT  NUMBER(4,2),
    DIEMCK NUMBER(4,2),
    DIEMTK  NUMBER(4,2),
    PRIMARY KEY (MASV, MAGV,MAHP, HK, NAM, MACT),
    FOREIGN KEY (MASV) REFERENCES ADMIN.SINHVIEN(MASV),
    FOREIGN KEY (MAHP) REFERENCES ADMIN.HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES ADMIN.NHANSU(MANV)
)


