ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;  

DROP TABLE DANGKY;
DROP TABLE DATTRONG.KHMO;
DROP TABLE DATTRONG.SINHVIEN;
DROP TABLE DATTRONG.PHANCONG;
DROP TABLE DATTRONG.HOCPHAN;
DROP TABLE DATTRONG.DONVI;
DROP TABLE DATTRONG.NHANSU;
CREATE TABLE DATTRONG.NHANSU (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI VARCHAR2(10),
    NGSINH DATE,
    PHUCAP NUMBER(10, 2),
    DT CHAR(10),
    VAITRO VARCHAR2(50),
    MADV VARCHAR2(20)
);

CREATE TABLE DATTRONG.SINHVIEN (
    MASV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(50),
    PHAI VARCHAR2(10),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT CHAR(10),
    MACT VARCHAR2(20),
    MANGANH VARCHAR2(20),
    SOTCTL NUMBER(3),
    DTBTL NUMBER(4, 2)
);

CREATE TABLE DATTRONG.DONVI (
    MADV VARCHAR2(20) PRIMARY KEY,
    TENDV VARCHAR2(50),
    TRGDV VARCHAR2(20),
    FOREIGN KEY (TRGDV) REFERENCES DATTRONG.NHANSU(MANV)
);

CREATE TABLE DATTRONG.HOCPHAN (
    MAHP VARCHAR2(20) PRIMARY KEY,
    TENHP VARCHAR2(50),
    SOTC NUMBER(2),
    STLT NUMBER(2),
    STTH NUMBER(2),
    SOSVTD NUMBER(3),
    MADV VARCHAR2(20),
    FOREIGN KEY (MADV) REFERENCES DATTRONG.DONVI(MADV)
);

CREATE TABLE DATTRONG.KHMO (
    MAHP VARCHAR2(20),
    HK VARCHAR2(10),
    NAM VARCHAR2(4),
    MACT VARCHAR2(20),
    PRIMARY KEY (MAHP, HK, NAM, MACT),
    FOREIGN KEY (MAHP) REFERENCES DATTRONG.HOCPHAN(MAHP)
);

CREATE TABLE DATTRONG.PHANCONG (
    MAGV VARCHAR2(20),
    MAHP VARCHAR2(20),
    HK VARCHAR2(10),
    NAM VARCHAR2(4),
    MACT VARCHAR2(20),
    PRIMARY KEY (MAGV,MAHP, HK, NAM, MACT),
    FOREIGN KEY (MAHP) REFERENCES DATTRONG.HOCPHAN(MAHP),
    FOREIGN KEY(MAGV) REFERENCES DATTRONG.NHANSU(MANV)
)

CREATE TABLE DATTRONG.DANGKY (
    MASV VARCHAR(20),
    MAGV VARCHAR2(20),
    MAHP VARCHAR2(20),
    HK VARCHAR2(10),
    NAM VARCHAR2(4),
    MACT VARCHAR2(20),
    DIEMTHI NUMBER(2,4),
    DIEMQT  NUMBER(2,4),
    DIEMCK NUMBER(2,4),
    DIEMTK  NUMBER(2,4),
    PRIMARY KEY (MASV, MAGV,MAHP, HK, NAM, MACT),
    FOREIGN KEY (MASV) REFERENCES DATTRONG.SINHVIEN(MASV),
    FOREIGN KEY (MAHP) REFERENCES DATTRONG.HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES DATTRONG.NHANSU(MANV)
)

CREATE USER HS1 IDENTIFIED BY HK1;
GRANT CONNECT, RESOURCE TO HS1;
GRANT CREATE SESSION TO HS1;
CREATE ROLE HS;
GRANT HS TO HS1;
GRANT CONNECT, RESOURCE TO HS;
GRANT CREATE SESSION TO HS;
DROP ROLE HS;
CREATE OR REPLACE VIEW INF_HS
AS
(
SELECT * FROM DATTRONG.SINHVIEN
);
drop view INF_HS;
GRANT SELECT(MASV) ON INF_HS TO HS1;

REVOKE SELECT ON DATTRONG.SINHVIEN FROM HS1;